print("Content-type: text/html\r\n\r\n")

print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("<title>CGI Python Test</title>")
print("</head>")
print("<body>")
print("<h2>Hello World! This is my first CGI Python program</h2>")
print("</body>")
print("</html>")
